all:
	python makeEnXGlobal.py

clean:
	rm -rf affixcompress[0123].tmp word word2 oxt/dictionaries/en-x-global.* en-x-global.txt* en-x-global.dic en-x-global.aff ooo_global_english_dict.oxt oxt-en-x-global oxt-en
